# Generated by Django 4.0.4 on 2022-05-28 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joshua', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='items',
            table='my_items',
        ),
    ]
