# Generated by Django 4.0.4 on 2022-05-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joshua', '0002_alter_items_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=240)),
                ('password', models.CharField(max_length=240)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
